global_config:
  log_level: INFO
  retry_conn_interval: 60
  default_time_interval: 15
  log_path: "logs/"
  port: 9844

queries:
  - name: "Lockwaits"
    runs_on: ["production"]
    time_interval: 10
    timeout: 5 # Cancel the query if it runs longer than 5 seconds
    query: |
      select
        count(*) count,
        coalesce(max(LOCK_WAIT_ELAPSED_TIME), 0) max_time
      from
        SYSIBMADM.MON_LOCKWAITS
    gauges:
      - name: "db2_lockwaits_count"
        desc: "Amount of lockwaits"
        col: 1

      - name: "db2_lockwaits_maxwait_seconds"
        desc: "Maximum number of seconds apps are waiting to get lock"
        col: 2
        extra_labels:
          time: "seconds"

  - name: "Applications count"
    runs_on: []
    time_interval: 15
    query: |
      SELECT
      count(*) as count,
      workload_occurrence_state,
      application_name
      FROM TABLE(MON_GET_CONNECTION(cast(NULL as bigint), -1))
      WHERE NOT REGEXP_LIKE(application_name, '^[0-9\.].*')
      AND application_name <> 'DB2PROM'
      GROUP BY application_name, workload_occurrence_state
      UNION
      SELECT
      count(*) as count,
      workload_occurrence_state,
      'FEDERATION' as application_name
      FROM TABLE(MON_GET_CONNECTION(cast(NULL as bigint), -1))
      WHERE REGEXP_LIKE(application_name, '^[0-9\.].*')
      GROUP BY workload_occurrence_state
    gauges:
      - name: "db2_applications_count"
        desc: "Amount of applications connected per state"
        col: 1
        extra_labels:
          appstate: "$2"
          appname: "$3"

  - name: "Log Utilization"
    runs_on: ["production"]
    time_interval: 15
    query: |
      SELECT LOG_UTILIZATION_PERCENT
      FROM SYSIBMADM.LOG_UTILIZATION
    gauges:
      - name: "db2_log_utilization_percent"
        desc: "Log utilization percentage"
        col: 1

  - name: "Active Connections"
    runs_on: ["production"]
    time_interval: 30
    query: |
      SELECT COUNT(*) AS active_connections FROM SYSIBMADM.APPLICATIONS
    gauges:
      - name: "db2_active_connections"
        desc: "Number of active connections"
        col: 1

  - name: "Tablespace Utilization"
    runs_on: ["production"]
    time_interval: 60
    query: |
      SELECT
        TBSP_NAME,
        TBSP_USED_SIZE_KB,
        TBSP_TOTAL_SIZE_KB
      FROM SYSIBMADM.TBSP_UTILIZATION
    gauges:
      - name: "db2_tablespace_used_size"
        desc: "Used size of the tablespace in KB"
        col: 2
        extra_labels:
          tablespace: "$1"
          
      - name: "db2_tablespace_total_size"
        desc: "Total size of the tablespace in KB"
        col: 3
        extra_labels:
          tablespace: "$1"

  - name: "Transaction Log Usage"
    runs_on: ["production"]
    time_interval: 30
    query: |
      SELECT
        TOTAL_LOG_USED_KB,
        TOTAL_LOG_AVAILABLE_KB
      FROM SYSIBMADM.LOG_UTILIZATION
    gauges:
      - name: "db2_total_log_used"
        desc: "Total log space used in KB"
        col: 1

      - name: "db2_total_log_available"
        desc: "Total log space available in KB"
        col: 2

  - name: "DB2 Start Time"
    runs_on: []
    time_interval: 60
    query: |
      SELECT
        UNIX_TIMESTAMP(DB2START_TIME) AS start_time
      FROM TABLE (MON_GET_INSTANCE(-2))
    gauges:
      - name: "db2_up_since_seconds"
        desc: "Unix timestamp when the DB2 instance started"
        col: 1

connections:
  - db_host: "192.168.50.253"
    db_name: "sample"
    db_port: 50000
    db_user: "DB2INST1"
    db_passwd: "mypassword"
    tags: [production, proddb1]
    extra_labels:
      dbinstance: db2inst1
      dbenv: production
